alias pacu='sudo pacman -Syu'
alias paci='sudo pacman -S'
alias pacid='sudo pacman -S --asdeps'
alias pacr='sudo pacman -Rsn'
alias pacs='pacman -Ss'
alias paco='pacman -Si'
alias pacq='pacman -Qsq'
alias pacl='pacman -Ql'
# pacman -Qo /usr/bin/fire
alias gpuoff='sudo /usr/share/acpi_call/examples/turn_off_gpu.sh &> /dev/null'
